//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CALENDAR
    {
        public int eventID { get; set; }
        [Display(Name = "Event Header")]
        public string eventHeader { get; set; }
        [Display(Name = "Event Description")]
        public string eventDescription { get; set; }
        [Display(Name = "Start Date")]
        public Nullable<System.DateTime> eventStart { get; set; }
        [Display(Name = "End Date")]
        public Nullable<System.DateTime> eventEnd { get; set; }
    }
}
