//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FISCALYEAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FISCALYEAR()
        {
            this.CHARTS = new HashSet<CHART>();
            this.GOALACTUALS = new HashSet<GOALACTUAL>();
            this.QUARTEROPTIONS = new HashSet<QUARTEROPTION>();
        }
    
        public int fiscalYearID { get; set; }
        [Display(Name = "Fiscal Year")]
        public int fiscalYear1 { get; set; }
        public Nullable<int> subcategoryID { get; set; }
        public Nullable<int> quarteroptionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHART> CHARTS { get; set; }
        public virtual QUARTEROPTION QUARTEROPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOALACTUAL> GOALACTUALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUARTEROPTION> QUARTEROPTIONS { get; set; }
    }
}
