//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GOALACTUAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOALACTUAL()
        {
            this.CHARTS = new HashSet<CHART>();
        }
    
        public int goalActualID { get; set; }
        [Display(Name = "Goal")]
        public string goalValue { get; set; }
        [Display(Name = "Actual")]
        public string actualGoal { get; set; }
        [Display(Name = "Team")]
        public Nullable<int> teamID { get; set; }
        [Display(Name = "Workstream")]
        public Nullable<int> workstreamID { get; set; }
        [Display(Name = "Category")]
        public Nullable<int> categoryID { get; set; }
        [Display(Name = "Subcategory")]
        public Nullable<int> subcategoryID { get; set; }
        [Display(Name = "Fiscal Year")]
        public Nullable<int> fiscalYear1 { get; set; }
        [Display(Name = "Fiscal Year")]
        public Nullable<int> fiscalYearID { get; set; }
        [Display(Name = "Period")]
        public Nullable<int> quarteroptionID { get; set; }
    
        public virtual CATEGORy CATEGORy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHART> CHARTS { get; set; }
        public virtual FISCALYEAR FISCALYEAR { get; set; }
        public virtual QUARTEROPTION QUARTEROPTION { get; set; }
        public virtual SUBCATEGORy SUBCATEGORy { get; set; }
        public virtual TEAM TEAM { get; set; }
        public virtual WORKSTREAM WORKSTREAM { get; set; }
    }
}
