//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class QUARTEROPTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUARTEROPTION()
        {
            this.CHARTS = new HashSet<CHART>();
            this.FISCALYEARS = new HashSet<FISCALYEAR>();
            this.GOALACTUALS = new HashSet<GOALACTUAL>();
        }
    
        public int quarteroptionID { get; set; }
        [Display(Name = "Period")]
        public string quarteroptionName { get; set; }
        public Nullable<int> subcategoryID { get; set; }
        public Nullable<int> fiscalYearID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHART> CHARTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FISCALYEAR> FISCALYEARS { get; set; }
        public virtual FISCALYEAR FISCALYEAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOALACTUAL> GOALACTUALS { get; set; }
    }
}
